export const yearsByNumber = new Map ([
[0,'Primer Grupo'],
[1,'Segundo Grupo'],
[2,'Tercer Grupo'],
[3,'1er. Grado'],
[4,'2do. Grado'],
[5,'3er. Grado'],
[6,'4to. Grado'],
[7,'5to. Grado'],
[8,'6to. Grado'],
[9,'1er. Año'],
[10,'2do. Año'],
[11,'3er. Año'],
[12,'4to. Año de Ciencias'],
[13,'5to. Año de Ciencias'],
])
export const yearsByString = new Map ([
['Primer Grupo',0],
['Segundo Grupo',1],
['Tercer Grupo',2],
['1er. Grado',3],
['2do. Grado',4],
['3er. Grado',5],
['4to. Grado',6],
['5to. Grado',7],
['6to. Grado',8],
['1er. Año',9],
['2do. Año',10],
['3er. Año',11],
['4to. Año de Ciencias',12],
['5to. Año de Ciencias',13],
])
export const yearLabelValue = [
{value:0,label:'Primer Grupo'},
{value:1,label:'Segundo Grupo'},
{value:2,label:'Tercer Grupo'},
{value:3,label:'1er. Grado'},
{value:4,label:'2do. Grado'},
{value:5,label:'3er. Grado'},
{value:6,label:'4to. Grado'},
{value:7,label:'5to. Grado'},
{value:8,label:'6to. Grado'},
{value:9,label:'1er. Año'},
{value:10,label:'2do. Año'},
{value:11,label:'3er. Año'},
{value:12,label:'4to. Año de Ciencias'},
{value:13,label:'5to. Año de Ciencias'}
]